#!bin/bash

################################################################################
#
#  mk_config
#
#  Copyright (c) 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
#
################################################################################

################################################################################
# NOTE: You must fill in the following with the path to a copy of an
#       arm_eabi-2011.03 compiler
################################################################################
CROSS_COMPILER_PATH="<path/to/arm-eabi-2011.03>"
