#
# Copyright 2019 Amazon.com, Inc. or its Affiliates. All rights reserved.
#
LOCAL_PATH := $(GET_LOCAL_DIR)

INCLUDES_LTC_ROOT = -I$(LOCAL_PATH)
INCLUDES_LTC_HEADERS = -I$(LOCAL_PATH)/src/headers
INCLUDES += $(INCLUDES_LTC_ROOT) $(INCLUDES_LTC_HEADERS) -I$(LOCAL_PATH)/testprof/

# Default CFLAGS
CFLAGS += 	 \
		-Os \
		-funroll-loops \
		-fomit-frame-pointer \
		-ffunction-sections \
		-fdata-sections \
		-Wall  \
		-Wsign-compare \
		-Wshadow \
		-DLTC_SOURCE \
		-Wextra \
		-Wsystem-headers \
		-Wbad-function-cast \
		-Wcast-align \
		-Wstrict-prototypes \
		-Wpointer-arith \
		-Wno-type-limits



CFLAGS +=	-DLTC_SOURCE \
		-DLTC_NO_RAND \
		-DLTC_NO_FILE \
		-DUSE_LTM -DLTM_DESC \
		-D_WCHAR_T \
		-DLTC_CLEAN_STACK

UNUSED_OBJS += \
	$(LOCAL_PATH)/src/ciphers/aes/aes_enc.o \
	$(LOCAL_PATH)/src/hashes/md2.o \
	$(LOCAL_PATH)/src/hashes/md4.o \
	$(LOCAL_PATH)/src/hashes/md5.o \
	$(LOCAL_PATH)/src/hashes/rmd128.o \
	$(LOCAL_PATH)/src/hashes/rmd160.o \
	$(LOCAL_PATH)/src/hashes/rmd256.o \
	$(LOCAL_PATH)/src/hashes/rmd320.o \
	$(LOCAL_PATH)/src/hashes/sha1.o \
	$(LOCAL_PATH)/src/hashes/sha2/sha224.o \
	$(LOCAL_PATH)/src/hashes/sha2/sha384.o \
	$(LOCAL_PATH)/src/hashes/sha2/sha512_224.o \
	$(LOCAL_PATH)/src/hashes/sha2/sha512_256.o \
	$(LOCAL_PATH)/src/hashes/sha2/sha512.o \
	$(LOCAL_PATH)/src/hashes/tiger.o \
	$(LOCAL_PATH)/src/hashes/whirl/whirl.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_add_aad.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_add_nonce.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_done.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_init.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_memory.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_memory_ex.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_process.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_reset.o \
	$(LOCAL_PATH)/src/encauth/ccm/ccm_test.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_addheader.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_decrypt.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_decrypt_verify_memory.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_done.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_encrypt_authenticate_memory.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_encrypt.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_init.o \
	$(LOCAL_PATH)/src/encauth/eax/eax_test.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_add_aad.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_add_iv.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_done.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_gf_mult.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_init.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_memory.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_mult_h.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_process.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_reset.o \
	$(LOCAL_PATH)/src/encauth/gcm/gcm_test.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_add_aad.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_decrypt.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_decrypt_last.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_decrypt_verify_memory.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_done.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_encrypt_authenticate_memory.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_encrypt.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_encrypt_last.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_init.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_int_aad_add_block.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_int_calc_offset_zero.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_int_ntz.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_int_xor_blocks.o \
	$(LOCAL_PATH)/src/encauth/ocb3/ocb3_test.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_decrypt.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_decrypt_verify_memory.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_done_decrypt.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_done_encrypt.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_encrypt_authenticate_memory.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_encrypt.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_init.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_ntz.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_shift_xor.o \
	$(LOCAL_PATH)/src/encauth/ocb/ocb_test.o \
	$(LOCAL_PATH)/src/encauth/ocb/s_ocb_done.o \
	$(LOCAL_PATH)/src/modes/cbc/cbc_decrypt.o \
	$(LOCAL_PATH)/src/modes/cbc/cbc_done.o \
	$(LOCAL_PATH)/src/modes/cbc/cbc_encrypt.o \
	$(LOCAL_PATH)/src/modes/cbc/cbc_getiv.o \
	$(LOCAL_PATH)/src/modes/cbc/cbc_setiv.o \
	$(LOCAL_PATH)/src/modes/cbc/cbc_start.o \
	$(LOCAL_PATH)/src/modes/cfb/cfb_decrypt.o \
	$(LOCAL_PATH)/src/modes/cfb/cfb_done.o \
	$(LOCAL_PATH)/src/modes/cfb/cfb_encrypt.o \
	$(LOCAL_PATH)/src/modes/cfb/cfb_getiv.o \
	$(LOCAL_PATH)/src/modes/cfb/cfb_setiv.o \
	$(LOCAL_PATH)/src/modes/cfb/cfb_start.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_decrypt.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_done.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_encrypt.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_getiv.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_setiv.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_start.o \
	$(LOCAL_PATH)/src/modes/ctr/ctr_test.o \
	$(LOCAL_PATH)/src/modes/ecb/ecb_decrypt.o \
	$(LOCAL_PATH)/src/modes/ecb/ecb_done.o \
	$(LOCAL_PATH)/src/modes/ecb/ecb_encrypt.o \
	$(LOCAL_PATH)/src/modes/ecb/ecb_start.o \
	$(LOCAL_PATH)/src/modes/f8/f8_decrypt.o \
	$(LOCAL_PATH)/src/modes/f8/f8_done.o \
	$(LOCAL_PATH)/src/modes/f8/f8_encrypt.o \
	$(LOCAL_PATH)/src/modes/f8/f8_getiv.o \
	$(LOCAL_PATH)/src/modes/f8/f8_setiv.o \
	$(LOCAL_PATH)/src/modes/f8/f8_start.o \
	$(LOCAL_PATH)/src/modes/f8/f8_test_mode.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_decrypt.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_done.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_encrypt.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_getiv.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_process.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_setiv.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_start.o \
	$(LOCAL_PATH)/src/modes/lrw/lrw_test.o \
	$(LOCAL_PATH)/src/modes/ofb/ofb_decrypt.o \
	$(LOCAL_PATH)/src/modes/ofb/ofb_done.o \
	$(LOCAL_PATH)/src/modes/ofb/ofb_encrypt.o \
	$(LOCAL_PATH)/src/modes/ofb/ofb_getiv.o \
	$(LOCAL_PATH)/src/modes/ofb/ofb_setiv.o \
	$(LOCAL_PATH)/src/modes/ofb/ofb_start.o \
	$(LOCAL_PATH)/src/modes/xts/xts_decrypt.o \
	$(LOCAL_PATH)/src/modes/xts/xts_done.o \
	$(LOCAL_PATH)/src/modes/xts/xts_encrypt.o \
	$(LOCAL_PATH)/src/modes/xts/xts_init.o \
	$(LOCAL_PATH)/src/modes/xts/xts_mult_x.o \
	$(LOCAL_PATH)/src/modes/xts/xts_test.o \
	$(LOCAL_PATH)/src/pk/dh/dh.o \
	$(LOCAL_PATH)/src/pk/dh/dh_static.o \
	$(LOCAL_PATH)/src/pk/dh/dh_sys.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_decrypt_key.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_encrypt_key.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_export.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_free.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_import.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_make_key.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_shared_secret.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_sign_hash.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_verify_hash.o \
	$(LOCAL_PATH)/src/pk/dsa/dsa_verify_key.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_ansi_x963_export.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_ansi_x963_import.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_decrypt_key.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_encrypt_key.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_export.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_free.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_get_size.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_import.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_make_key.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_shared_secret.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_sign_hash.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_sizes.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_test.o \
	$(LOCAL_PATH)/src/pk/ecc/ecc_verify_hash.o \
	$(LOCAL_PATH)/src/pk/katja/katja_decrypt_key.o \
	$(LOCAL_PATH)/src/pk/katja/katja_encrypt_key.o \
	$(LOCAL_PATH)/src/pk/katja/katja_export.o \
	$(LOCAL_PATH)/src/pk/katja/katja_exptmod.o \
	$(LOCAL_PATH)/src/pk/katja/katja_free.o \
	$(LOCAL_PATH)/src/pk/katja/katja_import.o \
	$(LOCAL_PATH)/src/pk/katja/katja_make_key.o \
	$(LOCAL_PATH)/src/ciphers/anubis.o \
	$(LOCAL_PATH)/src/ciphers/blowfish.o \
	$(LOCAL_PATH)/src/ciphers/camellia.o \
	$(LOCAL_PATH)/src/ciphers/cast5.o \
	$(LOCAL_PATH)/src/ciphers/des.o \
	$(LOCAL_PATH)/src/ciphers/kasumi.o \
	$(LOCAL_PATH)/src/ciphers/khazad.o \
	$(LOCAL_PATH)/src/ciphers/kseed.o \
	$(LOCAL_PATH)/src/ciphers/multi2.o \
	$(LOCAL_PATH)/src/ciphers/noekeon.o \
	$(LOCAL_PATH)/src/ciphers/rc2.o \
	$(LOCAL_PATH)/src/ciphers/rc5.o \
	$(LOCAL_PATH)/src/ciphers/rc6.o \
	$(LOCAL_PATH)/src/ciphers/safer/safer.o \
	$(LOCAL_PATH)/src/ciphers/safer/saferp.o \
	$(LOCAL_PATH)/src/ciphers/skipjack.o \
	$(LOCAL_PATH)/src/ciphers/twofish/twofish.o \
	$(LOCAL_PATH)/src/ciphers/xtea.o \

OBJS += \
	$(LOCAL_PATH)/src/ciphers/aes/aes.o \
	$(LOCAL_PATH)/src/hashes/sha2/sha256.o \
	$(LOCAL_PATH)/src/hashes/chc/chc.o \
	$(LOCAL_PATH)/src/hashes/helper/hash_file.o \
	$(LOCAL_PATH)/src/hashes/helper/hash_filehandle.o \
	$(LOCAL_PATH)/src/hashes/helper/hash_memory.o \
	$(LOCAL_PATH)/src/hashes/helper/hash_memory_multi.o \
	$(LOCAL_PATH)/src/mac/f9/f9_done.o \
	$(LOCAL_PATH)/src/mac/f9/f9_file.o \
	$(LOCAL_PATH)/src/mac/f9/f9_init.o \
	$(LOCAL_PATH)/src/mac/f9/f9_memory.o \
	$(LOCAL_PATH)/src/mac/f9/f9_memory_multi.o \
	$(LOCAL_PATH)/src/mac/f9/f9_process.o \
	$(LOCAL_PATH)/src/mac/f9/f9_test.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_done.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_file.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_init.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_memory.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_memory_multi.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_process.o \
	$(LOCAL_PATH)/src/mac/hmac/hmac_test.o \
	$(LOCAL_PATH)/src/mac/omac/omac_done.o \
	$(LOCAL_PATH)/src/mac/omac/omac_file.o \
	$(LOCAL_PATH)/src/mac/omac/omac_init.o \
	$(LOCAL_PATH)/src/mac/omac/omac_memory.o \
	$(LOCAL_PATH)/src/mac/omac/omac_memory_multi.o \
	$(LOCAL_PATH)/src/mac/omac/omac_process.o \
	$(LOCAL_PATH)/src/mac/omac/omac_test.o \
	$(LOCAL_PATH)/src/mac/pelican/pelican.o \
	$(LOCAL_PATH)/src/mac/pelican/pelican_memory.o \
	$(LOCAL_PATH)/src/mac/pelican/pelican_test.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_done.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_file.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_init.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_memory.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_memory_multi.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_ntz.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_process.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_shift_xor.o \
	$(LOCAL_PATH)/src/mac/pmac/pmac_test.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_done.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_file.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_init.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_memory.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_memory_multi.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_process.o \
	$(LOCAL_PATH)/src/mac/xcbc/xcbc_test.o \
	$(LOCAL_PATH)/src/math/fp/ltc_ecc_fp_mulmod.o \
	$(LOCAL_PATH)/src/math/gmp_desc.o \
	$(LOCAL_PATH)/src/math/ltm_desc.o \
	$(LOCAL_PATH)/src/math/multi.o \
	$(LOCAL_PATH)/src/math/rand_bn.o \
	$(LOCAL_PATH)/src/math/rand_prime.o \
	$(LOCAL_PATH)/src/math/tfm_desc.o \
	$(LOCAL_PATH)/src/misc/adler32.o \
	$(LOCAL_PATH)/src/misc/base64/base64_decode.o \
	$(LOCAL_PATH)/src/misc/base64/base64_encode.o \
	$(LOCAL_PATH)/src/misc/burn_stack.o \
	$(LOCAL_PATH)/src/misc/crc32.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_argchk.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_cipher_descriptor.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_cipher_is_valid.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_constants.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_cipher_any.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_cipher.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_cipher_id.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_hash_any.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_hash.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_hash_id.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_hash_oid.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_find_prng.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_fsa.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_hash_descriptor.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_hash_is_valid.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_inits.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_ltc_mp_descriptor.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_prng_descriptor.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_prng_is_valid.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_register_cipher.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_register_hash.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_register_prng.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_sizes.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_unregister_cipher.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_unregister_hash.o \
	$(LOCAL_PATH)/src/misc/crypt/crypt_unregister_prng.o \
	$(LOCAL_PATH)/src/misc/error_to_string.o \
	$(LOCAL_PATH)/src/misc/hkdf/hkdf.o \
	$(LOCAL_PATH)/src/misc/hkdf/hkdf_test.o \
	$(LOCAL_PATH)/src/misc/mem_neq.o \
	$(LOCAL_PATH)/src/misc/pkcs5/pkcs_5_1.o \
	$(LOCAL_PATH)/src/misc/pkcs5/pkcs_5_2.o \
	$(LOCAL_PATH)/src/misc/pkcs5/pkcs_5_test.o \
	$(LOCAL_PATH)/src/misc/pk_get_oid.o \
	$(LOCAL_PATH)/src/misc/zeromem.o \
	$(LOCAL_PATH)/src/pk/asn1/der/bit/der_decode_bit_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/bit/der_decode_raw_bit_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/bit/der_encode_bit_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/bit/der_encode_raw_bit_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/bit/der_length_bit_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/boolean/der_decode_boolean.o \
	$(LOCAL_PATH)/src/pk/asn1/der/boolean/der_encode_boolean.o \
	$(LOCAL_PATH)/src/pk/asn1/der/boolean/der_length_boolean.o \
	$(LOCAL_PATH)/src/pk/asn1/der/choice/der_decode_choice.o \
	$(LOCAL_PATH)/src/pk/asn1/der/ia5/der_decode_ia5_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/ia5/der_encode_ia5_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/ia5/der_length_ia5_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/integer/der_decode_integer.o \
	$(LOCAL_PATH)/src/pk/asn1/der/integer/der_encode_integer.o \
	$(LOCAL_PATH)/src/pk/asn1/der/integer/der_length_integer.o \
	$(LOCAL_PATH)/src/pk/asn1/der/object_identifier/der_decode_object_identifier.o \
	$(LOCAL_PATH)/src/pk/asn1/der/object_identifier/der_encode_object_identifier.o \
	$(LOCAL_PATH)/src/pk/asn1/der/object_identifier/der_length_object_identifier.o \
	$(LOCAL_PATH)/src/pk/asn1/der/octet/der_decode_octet_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/octet/der_encode_octet_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/octet/der_length_octet_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/printable_string/der_decode_printable_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/printable_string/der_encode_printable_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/printable_string/der_length_printable_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_decode_sequence_ex.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_decode_sequence_flexi.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_decode_sequence_multi.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_decode_subject_public_key_info.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_encode_sequence_ex.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_encode_sequence_multi.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_encode_subject_public_key_info.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_length_sequence.o \
	$(LOCAL_PATH)/src/pk/asn1/der/sequence/der_sequence_free.o \
	$(LOCAL_PATH)/src/pk/asn1/der/set/der_encode_set.o \
	$(LOCAL_PATH)/src/pk/asn1/der/set/der_encode_setof.o \
	$(LOCAL_PATH)/src/pk/asn1/der/short_integer/der_decode_short_integer.o \
	$(LOCAL_PATH)/src/pk/asn1/der/short_integer/der_encode_short_integer.o \
	$(LOCAL_PATH)/src/pk/asn1/der/short_integer/der_length_short_integer.o \
	$(LOCAL_PATH)/src/pk/asn1/der/teletex_string/der_decode_teletex_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/teletex_string/der_length_teletex_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/utctime/der_decode_utctime.o \
	$(LOCAL_PATH)/src/pk/asn1/der/utctime/der_encode_utctime.o \
	$(LOCAL_PATH)/src/pk/asn1/der/utctime/der_length_utctime.o \
	$(LOCAL_PATH)/src/pk/asn1/der/utf8/der_decode_utf8_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/utf8/der_encode_utf8_string.o \
	$(LOCAL_PATH)/src/pk/asn1/der/utf8/der_length_utf8_string.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_i2osp.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_mgf1.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_oaep_decode.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_oaep_encode.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_os2ip.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_pss_decode.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_pss_encode.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_v1_5_decode.o \
	$(LOCAL_PATH)/src/pk/pkcs1/pkcs_1_v1_5_encode.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_decrypt_key.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_encrypt_key.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_export.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_exptmod.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_free.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_get_size.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_import.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_make_key.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_sign_hash.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_sign_saltlen_get.o \
	$(LOCAL_PATH)/src/pk/rsa/rsa_verify_hash.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_is_valid_idx.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_map.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_mul2add.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_mulmod.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_mulmod_timing.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_points.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_projective_add_point.o \
	$(LOCAL_PATH)/src/pk/ecc/ltc_ecc_projective_dbl_point.o \
	$(LOCAL_PATH)/src/prngs/fortuna.o \
	$(LOCAL_PATH)/src/prngs/rc4.o \
	$(LOCAL_PATH)/src/prngs/rng_get_bytes.o \
	$(LOCAL_PATH)/src/prngs/rng_make_prng.o \
	$(LOCAL_PATH)/src/prngs/sober128.o \
	$(LOCAL_PATH)/src/prngs/sprng.o \
	$(LOCAL_PATH)/src/prngs/yarrow.o \
	$(LOCAL_PATH)/qsort.o
